<?php

namespace App\DemoData\Random\NameOptions;

class FindingPlaceNames
{
    /**
     * @return array<int, string>
     */
    public static function getNames(): array
    {
        return [
            'FossilRidge Excavations',
            'Paleopit Digs',
            'AncientLayers Quarry',
            'TriloTreasure Cove',
            'AmberHaven Fields',
            'DinoDust Bluffs',
            'Megalodon Marina',
            'PetrifiedWood Grove',
            'ShellShore Fossils',
            'TimeTravelers Canyon',
            'Coprolite Creek Beds',
            'AmmoniteAlcove',
            'FossilFrontier Ridge',
            'DinoTracks Tract',
            'TraceFossil Terraces',
            'CambrianCliffs Caves',
            'MosasaurMingle Marina',
            'AncientAbyss Abyss',
            'Paleogrove Park',
            'SharkTooth Shores',
            'TrilobiteTraverse Trails',
            'CoproliteCanyon Creek',
            'MesozoicMeadow',
            'MegafaunaMound',
            'GinkgoGrove Gardens',
            'PrehistoricPitstop',
            'FossilFormation Fields',
            'CretaceousCreekbank',
            'DinoDunes Desert',
            'PetrifiedPine Park',
            'PaleoPlains Preserve',
            'AmmoniteArchipelago',
            'JurassicJewel Junction',
            'TriloTreasure Tundra',
            'CoproliteCliffs Coast',
            'FossilFiesta Flats',
            'TimelessTrek Terrace',
            'GlossoGrove Gardens',
            'MesozoicMingle Meadows',
            'DinoDiscovery Depot',
            'FossilFrontier Foothills',
            'AncientAbyss Arch',
            'SharkTooth Summit',
            'CoproliteCrest Cave',
            'TriloTreasure Treetops',
            'FossilFormation Fields',
            'CretaceousCliffs Canyon',
            'DinoDig Dunes',
            'PetrifiedPine Plateau',
            'PaleoParadise Point',
            'JurassicJewel Junction',
            'TriloTreasure Tundra',
            'CoproliteCliffs Cove',
            'FossilFiesta Fields',
            'TimelessTrek Terrace',
            'GlossoGrove Gardens',
            'MesozoicMingle Meadows',
            'DinoDiscovery Depot',
            'FossilFrontier Foothills',
            'AncientAbyss Arch',
            'SharkTooth Summit',
            'CoproliteCrest Cave',
            'TriloTreasure Treetops',
            'DinoDig Dunes',
            'PetrifiedPine Plateau',
            'PaleoParadise Point',
            'CambrianCave Collectibles',
            'GlossoGrove Gardens',
            'FossilFrontier Foothills',
            'AncientAbyss Arch',
            'SharkTooth Summit',
            'CoproliteCrest Cove',
            'TriloTreasure Treetops',
            'DinoDig Dunes',
            'PetrifiedPine Plateau',
            'PaleoParadise Point',
            'CambrianCave Collectibles',
            'AmmoniteAlley Adventures',
            'TrilobiteTrail Treasures',
            'CoproliteCreek Collectibles',
            'TimeWarp Wells',
            'FossilFiesta Findings',
            'MesozoicMeadow Mementos',
            'DinoDiscovery Delights',
            'Paleontologists Playground',
            'AncientArtifact Acres',
            'PrehistoricPuzzle Park',
            'Megalodons Cove Collection',
            'PetrifiedPleasure Point',
            'GinkgoGrove Gatherings',
            'DinoDust Delve',
            'FossilizedFern Fields',
            'AmmoniteArch Adventures',
            'TrilobiteTrail Treasures',
            'CoproliteCreek Collectibles',
            'TimeWarp Wells',
            'FossilFiesta Findings',
            'MesozoicMeadow Mementos',
            'DinoDiscovery Delights',
            'Paleontologists Playground',
        ];
    }
}