<?php

namespace App\DemoData\Random\NameOptions;

class FormationNames
{
    /**
     * @return array<int, string>
     */
    public static function getNames(): array
    {
        return [
            'Burgess Shale',
            'Dinosaur Provincial Park',
            'Solnhofen Limestone',
            'La Brea Tar Pits',
            'Green River Formation',
            'Florissant Fossil Beds',
            'Hell Creek Formation',
            'Joggins Fossil Cliffs',
            'Yixian Formation',
            'Liaoning Province Fossil Beds',
            'Santana Formation',
            'Kem Kem Beds',
            'Jurassic Coast',
            'Mazon Creek',
            'Hunsrück Slate',
            'Crato Formation',
            'Ediacara Hills',
            'Hellnmaria Quarry',
            'Konservat-Lagerstätte',
            'Morrison Formation',
            'Karoo Supergroup',
            'Shishugou Formation',
            'Oker Quarry',
            'Sainte Marie-aux-Mines',
            'Hakel Quarry',
            'Bear Gulch Limestone',
            'Monte Bolca',
            'Dinosaur Ridge',
            'Bear Paw Shale',
            'Wheeler Shale',
            'Whitby Jet',
            'Lagerstätte Hoher Kranzberg',
            'Red Gulch Dinosaur Tracksite',
            'Elmo Formation',
            'Walcott Quarry',
            'Marmarth Research Foundation Quarry',
            'Black Hills Institute Quarry',
            'Jianshangou Beds',
            'Niobrara Chalk',
            'Puerco Pueblo Formation',
            'Yoho National Park',
            'Mirpurkhas Beds',
            'Karabastau Formation',
            'Toadstool Geologic Park',
            'Sihetun Fossil Beds',
            'Tugulu Group',
            'Nacimiento Formation',
            'Kootenay National Park',
            'Santana do Cariri Formation',
            'Talbragar Fossil Beds',
            'Upper Ordovician–Lower Silurian Kopanina Formation',
            'Qujing Biota',
            'Taynton Limestone',
            'Kemmerer Quarry',
            'Montevarchi Lagerstätte',
            'Strunian Formation',
            'Doushantuo Formation',
            'Dashankou Fossil Beds',
            'Guryul Ravine Fossil Assemblage',
            'Pliocene–Pleistocene Sarasota Formation',
            'Quarry 9',
            'Mistaken Point',
            'Franklin Mountains',
            'Sharktooth Hill',
            'Permian Reef Complex',
            'Monte San Giorgio',
            'Swauk Formation',
            'K/Pg Boundary',
            'Gansu Fossil Beds',
            'Mirpur Mathelo',
            'Delorme Formation',
            'Gogo Formation',
            'Upper Ordovician Bromide Formation',
            'Wheeler Formation',
            'Dinosaur Cove',
            'Greer Spring',
            'Saint-Jean Formation',
            'Naracoorte Caves',
            'Isle of Wight',
            'John Day Fossil Beds',
            'White River Group',
            'Chengjiang Fossil Site',
            'Guanling Formation',
            'La Meseta Formation',
            'Talbragar River Beds',
            'Waynesville Formation',
            'Kettner Quarry',
            'Bulman Formation',
            'Bromacker Quarry',
            'Ordovician–Silurian Fezouata Formation',
            'Juan de Fuca Ridge',
            'Pozo Formation',
            'Paleorrota Geopark',
            'Holzmaden',
            'Cedar Mountain Formation',
            'Arisaig Group',
            'Jingpohu Fossil Beds',
            'Plum Point',
            'Cretaceous Chalk',
            'Rancho La Brea',
        ];
    }
}