<?php

namespace App\DemoData\Random\NameOptions;

class GeniusNames
{
    /**
     * @return array<int, string>
     */
    public static function getNames(): array
    {
        return [
            'Tyrannosaurus',
            'Stegosaurus',
            'Triceratops',
            'Brachiosaurus',
            'Archaeopteryx',
            'Velociraptor',
            'Mammoth',
            'Saber-toothed Cat',
            'Ichthyosaur',
            'Plesiosaur',
            'Dimetrodon',
            'Dunkleosteus',
            'Australopithecus',
            'Tiktaalik',
            'Ambulocetus',
            'Basilosaurus',
            'Coelacanth',
            'Pteranodon',
            'Brontosaurus',
            'Homo naledi',
            'Parasaurolophus',
            'Deinonychus',
            'Giganotosaurus',
            'Liopleurodon',
            'Megalodon',
            'Iguanodon',
            'Apatosaurus',
            'Allosaurus',
            'Dilophosaurus',
            'Maiasaura',
            'Pachycephalosaurus',
            'Homo erectus',
            'Velociraptor',
            'Pterodactylus',
            'Dromaeosaurus',
            'Anomalocaris',
            'Heterodontosaurus',
            'Dinornis',
            'Glyptodon',
            'Oviraptor',
            'Edmontosaurus',
            'Carcharodontosaurus',
            'Sarcosuchus',
            'Homotherium',
            'Thylacoleo',
            'Diprotodon',
            'Paraceratherium',
            'Ediacaran Biota',
            'Pikaia',
            'Hallucigenia',
            'Opabinia',
            'Trilobites',
            'Ammonites',
            'Nautilus',
            'Helicoprion',
            'Camarasaurus',
            'Dinoflagellates',
            'Solenhofen Plattenkalk Fossils',
            'Thrinaxodon',
            'Sordes Pilosus',
            'Aegirocassis',
            'Dickinsonia',
            'Hallucigenia',
            'Aglaophyton',
            'Odontochile',
            'Pterichthyodes',
            'Elginerpeton',
            'Eurypterids',
            'Orthoceras',
            'Lepidodendron',
            'Dimorphodon',
            'Koolasuchus',
            'Charnia',
            'Cleistospermum',
            'Crocodylomorphs',
            'Eurypterus',
            'Eusthenopteron',
            'Fern Fossils',
            'Graptolites',
            'Horseshoe Crab',
            'Lepidodendron',
            'Megaloceros',
            'Mesonyx',
            'Mioplosus',
            'Pakicetus',
            'Placodermi',
            'Psittacosaurus',
            'Radiolarians',
            'Repenomamus',
            'Rhynie Chert',
            'Sabellidites',
            'Sauropelta',
            'Shark Teeth',
            'Spinosaurus',
            'Stylonurus',
            'Tiktaalik',
            'Titanothere',
            'Toxodon',
            'Xenacanthus',
            'Zygodactylus',
        ];
    }
}
