INSERT INTO `fossil_form_field` (`field_order`, `field_name`, `field_label`, `field_type`, `allow_blank`,
                                 `is_required_default`, `active`, `show_always`, `field_group`, `show_in_overview`)
VALUES (0, 'showInGallery', 'admin.formFields.showInGallery', 'BOOL', true, true, true, true, 'GENERAL', false),
       (1, 'number', 'admin.formFields.number', 'TEXT', false, true, true, true, 'GENERAL', true),
       (10, 'dateOfDiscovery', 'admin.formFields.dateOfDiscovery', 'DATE', true, true, true, false, 'DISCOVERY', false),
       (20, 'foundInCountry', 'admin.formFields.foundInCountry', 'TEXT', true, true, true, false, 'DISCOVERY', false),
       (30, 'findingPlace', 'admin.formFields.findingPlace', 'TEXT', true, true, true, false, 'DISCOVERY', true),
       (40, 'coordinates', 'admin.formFields.coordinates', 'TEXT', true, true, true, false, 'DISCOVERY', false),
       (50, 'findingNotes', 'admin.formFields.findingNotes', 'TEXTAREA', true, true, true, false, 'DISCOVERY', false),
       (60, 'earthAgeSystem', 'admin.formFields.system', 'TEXT', true, true, true, true, 'STRATIGRAPHY', false),
       (70, 'earthAgeSeries', 'admin.formFields.series', 'TEXT', true, true, true, true, 'STRATIGRAPHY', false),
       (80, 'earthAgeStage', 'admin.formFields.stage', 'TEXT', true, true, true, true, 'STRATIGRAPHY', true),
       (90, 'formation', 'admin.formFields.formation', 'TEXT', true, true, true, false, 'STRATIGRAPHY', false),
       (100, 'member', 'admin.formFields.member', 'TEXT', true, true, true, false, 'STRATIGRAPHY', false),
       (110, 'stratigraphicNotes', 'admin.formFields.stratigraphicNotes', 'TEXTAREA', true, true, true, false, 'STRATIGRAPHY', false),
       (120, 'empire', 'admin.formFields.empire', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (130, 'tribe', 'admin.formFields.tribe', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (140, 'class', 'admin.formFields.class', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (150, 'order', 'admin.formFields.order', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (160, 'family', 'admin.formFields.family', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (170, 'genius', 'admin.formFields.genius', 'TEXT', true, true, true, false, 'TAXONOMY', false),
       (180, 'species', 'admin.formFields.species', 'TEXT', true, true, true, false, 'TAXONOMY', true),
       (190, 'subspecies', 'admin.formFields.subspecies', 'TEXT', true, true, true, false, 'TAXONOMY', true),
       (200, 'size', 'admin.formFields.size', 'TEXT', true, true, true, false, 'TAXONOMY', false),
       (210, 'taxonomyNotes', 'admin.formFields.taxonomyNotes', 'TEXTAREA', true, true, true, false, 'TAXONOMY', false);

-- INSERT INTO `earth_age_system` (`id`, `name`, `active`, `custom`)
-- VALUES (1, 'Quartär', false, false),
--        (2, 'Neogen', false, false),
--        (3, 'Paläogen', false, false),
--        (4, 'Kreide', true, false),
--        (5, 'Jura', true, false),
--        (6, 'Trias', true, false),
--        (7, 'Perm', true, false),
--        (8, 'Karbon', true, false),
--        (9, 'Devon', true, false),
--        (10, 'Silur', true, false),
--        (11, 'Ordovizium', true, false),
--        (12, 'Kambrium', true, false),
--        (13, 'Präkambrium', true, false);

-- INSERT INTO `earth_age_series` (`id`, `name`, `earth_age_system_id`)
-- VALUES (1, 'Holozän', 1),
--        (2, 'Pleistozän', 1),
--        (3, 'Pliozän', 2),
--        (4, 'Miozän', 2),
--        (5, 'Oligozän', 3),
--        (6, 'Eozän', 3),
--        (7, 'Paläozän', 3),
--        (8, 'Oberkreide', 4),
--        (9, 'Unterkreide', 4),
--        (10, 'Oberjura', 5),
--        (11, 'Mitteljura', 5),
--        (12, 'Unterjura', 5),
--        (13, 'Obertrias', 6),
--        (14, 'Mitteltrias', 6),
--        (15, 'Untertrias', 6),
--        (16, 'Lopingium', 7),
--        (17, 'Guadalupium', 7),
--        (18, 'Cisuralium', 7),
--        (19, 'Pennsylvanium', 8),
--        (20, 'Mississippium', 8),
--        (21, 'Oberdevon', 9),
--        (22, 'Mitteldevon', 9),
--        (23, 'Unterdevon', 9),
--        (24, 'Pridoli', 10),
--        (25, 'Ludlow', 10),
--        (26, 'Wenlock', 10),
--        (27, 'Llandovery', 10),
--        (28, 'Ober-ordovizium', 11),
--        (29, 'Mittel-ordovizium', 11),
--        (30, 'Unter-ordovizium', 11),
--        (31, 'Furongium', 12),
--        (32, 'Miaolingium', 12),
--        (33, '2. Serie', 12),
--        (34, 'Terreneuvium', 12);

-- INSERT INTO `earth_age_stage` (`id`, `name`, `earth_age_series_id`, `custom`)
-- VALUES (1, 'Meghalayum', 1, false),
--        (2, 'Nordgrippium', 1, false),
--        (3, 'Grönlandium', 1, false),
--        (4, 'Tarantium', 2, false),
--        (5, 'Ionium', 2, false),
--        (6, 'Calabrium', 2, false),
--        (7, 'Gelasium', 2, false),
--        (8, 'Piacenzium', 3, false),
--        (9, 'Zancleum', 3, false),
--        (10, 'Messinium', 4, false),
--        (11, 'Tortonium', 4, false),
--        (12, 'Serravallium', 4, false),
--        (13, 'Langhium', 4, false),
--        (14, 'Burdigalium', 4, false),
--        (15, 'Aquitanium', 4, false),
--        (16, 'Chattium', 5, false),
--        (17, 'Rupelium', 5, false),
--        (18, 'Priabonium', 6, false),
--        (19, 'Bartonium', 6, false),
--        (20, 'Lutetium', 6, false),
--        (21, 'Ypresium', 6, false),
--        (22, 'Thanetium', 7, false),
--        (23, 'Seelandium', 7, false),
--        (24, 'Danium', 7, false),
--        (25, 'Maastrichtium', 8, false),
--        (26, 'Campanium', 8, false),
--        (27, 'Santonium', 8, false),
--        (28, 'Coniacium', 8, false),
--        (29, 'Turonium', 8, false),
--        (30, 'Cenomanium', 8, false),
--        (31, 'Albium', 9, false),
--        (32, 'Aptium', 9, false),
--        (33, 'Barremium', 9, false),
--        (34, 'Hauterivium', 9, false),
--        (35, 'Valanginium', 9, false),
--        (36, 'Berriasium', 9, false),
--        (37, 'Tithonium', 10, false),
--        (38, 'Kimmeridgium', 10, false),
--        (39, 'Oxfordium', 10, false),
--        (40, 'Callovium', 11, false),
--        (41, 'Bathonium', 11, false),
--        (42, 'Bajocium', 11, false),
--        (43, 'Aalenium', 11, false),
--        (44, 'Toarcium', 12, false),
--        (45, 'Pliensbachium', 12, false),
--        (46, 'Sinemurium', 12, false),
--        (47, 'Hettangium', 12, false),
--        (48, 'Rhaetium', 13, false),
--        (49, 'Norium', 13, false),
--        (50, 'Karnium', 13, false),
--        (51, 'Ladinium', 14, false),
--        (52, 'Anisium', 14, false),
--        (53, 'Olenekium', 15, false),
--        (54, 'Indusium', 15, false),
--        (55, 'Changhsingium', 16, false),
--        (56, 'Wuchiapingium', 16, false),
--        (57, 'Capitanium', 17, false),
--        (58, 'Wordium', 17, false),
--        (59, 'Roadium', 17, false),
--        (60, 'Kungurium', 18, false),
--        (61, 'Artinskium', 18, false),
--        (62, 'Sakmarium', 18, false),
--        (63, 'Asselium', 18, false),
--        (64, 'Oberes Pennsylvanium > Gzhelium', 19, false),
--        (65, 'Oberes Pennsylvanium > Kasimovium', 19, false),
--        (66, 'Mittleres Pennsylvanium > Moskovium', 19, false),
--        (67, 'Unteres Pennsylvanium > Bashkirium', 19, false),
--        (68, 'Oberes Mississippium > Serpukhovium', 20, false),
--        (69, 'Mittleres Mississippium > Viséum', 20, false),
--        (70, 'Unteres Mississippium > Tournaisium', 20, false),
--        (71, 'Famennium', 21, false),
--        (72, 'Frasnium', 21, false),
--        (73, 'Givetium', 22, false),
--        (74, 'Eifelium', 22, false),
--        (75, 'Emsium', 23, false),
--        (76, 'Pragium', 23, false),
--        (77, 'Lochkovium', 23, false),
--        (78, 'Pridolium', 24, false),
--        (79, 'Ludfordium', 25, false),
--        (80, 'Gorstium', 25, false),
--        (81, 'Homerium', 26, false),
--        (82, 'Sheinwoodium', 26, false),
--        (83, 'Telychium', 27, false),
--        (84, 'Aeronium', 27, false),
--        (85, 'Rhuddanium', 27, false),
--        (86, 'Hirnantium', 28, false),
--        (87, 'Katium', 28, false),
--        (88, 'Sandbium', 28, false),
--        (89, 'Darriwilium', 29, false),
--        (90, 'Dapingium', 29, false),
--        (91, 'Floium', 30, false),
--        (92, 'Tremadocium', 30, false),
--        (93, '10. Stufe', 31, false),
--        (94, 'Jiangshanium', 31, false),
--        (95, 'Paibium', 31, false),
--        (96, 'Guzhangium', 32, false),
--        (97, 'Drumium', 32, false),
--        (98, 'Wuliuum', 32, false),
--        (99, '4. Stufe', 33, false),
--        (100, '3. Stufe', 33, false),
--        (101, '2. Stufe', 34, false),
--        (102, 'Fortunium', 34, false);

