INSERT INTO `fossil_form_field` (`field_order`, `field_name`, `field_label`, `field_type`, `allow_blank`,
                                 `is_required_default`, `active`, `show_always`, `field_group`, `show_in_overview`)
VALUES (0, 'showInGallery', 'admin.formFields.showInGallery', 'BOOL', true, true, true, true, 'GENERAL', false),
       (1, 'number', 'admin.formFields.number', 'TEXT', false, true, true, true, 'GENERAL', true),
       (10, 'dateOfDiscovery', 'admin.formFields.dateOfDiscovery', 'DATE', true, true, true, false, 'DISCOVERY', false),
       (20, 'foundInCountry', 'admin.formFields.foundInCountry', 'TEXT', true, true, true, false, 'DISCOVERY', false),
       (30, 'findingPlace', 'admin.formFields.findingPlace', 'TEXT', true, true, true, false, 'DISCOVERY', true),
       (40, 'coordinates', 'admin.formFields.coordinates', 'TEXT', true, true, true, false, 'DISCOVERY', false),
       (50, 'findingNotes', 'admin.formFields.findingNotes', 'TEXTAREA', true, true, true, false, 'DISCOVERY', false),
       (60, 'eaSystem', 'admin.formFields.system', 'SYSTEM', true, true, true, true, 'STRATIGRAPHY', false),
       (70, 'eaSeries', 'admin.formFields.series', 'SERIES', true, true, true, true, 'STRATIGRAPHY', false),
       (80, 'eaStage', 'admin.formFields.stage', 'STAGE', true, true, true, true, 'STRATIGRAPHY', true),
       (90, 'formation', 'admin.formFields.formation', 'TEXT', true, true, true, false, 'STRATIGRAPHY', false),
       (100, 'member', 'admin.formFields.member', 'TEXT', true, true, true, false, 'STRATIGRAPHY', false),
       (110, 'stratigraphicNotes', 'admin.formFields.stratigraphicNotes', 'TEXTAREA', true, true, true, false, 'STRATIGRAPHY', false),
       (120, 'empire', 'admin.formFields.empire', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (130, 'tribe', 'admin.formFields.tribe', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (140, 'class', 'admin.formFields.class', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (150, 'order', 'admin.formFields.order', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (160, 'family', 'admin.formFields.family', 'TEXT', true, true, false, false, 'TAXONOMY', false),
       (170, 'genius', 'admin.formFields.genius', 'TEXT', true, true, true, false, 'TAXONOMY', false),
       (180, 'species', 'admin.formFields.species', 'TEXT', true, true, true, false, 'TAXONOMY', true),
       (190, 'subspecies', 'admin.formFields.subspecies', 'TEXT', true, true, true, false, 'TAXONOMY', true),
       (200, 'size', 'admin.formFields.size', 'TEXT', true, true, true, false, 'TAXONOMY', false),
       (210, 'taxonomyNotes', 'admin.formFields.taxonomyNotes', 'TEXTAREA', true, true, true, false, 'TAXONOMY', false);
