name: Build

on:
    workflow_call:

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build-fossil-catalog:
        timeout-minutes: 36
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup PHP
                id: setup-php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: mbstring, intl, pdo_mysql, ctype, gd, iconv, yaml, zip

            -   name: Install composer dependencies
                run: |
                    composer install

            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install dependencies
                run: |
                    cd javascript
                    npm install

            -   name: Build JS
                run: |
                    cd javascript
                    npm run build

            -   name: Install translations
                run: |
                    php bin/console app:install-translations