name: PHP

on:
    workflow_call:

jobs:
    CodeStyle-PhpStan-UnitTests:
        runs-on: ubuntu-latest
        env:
            DB_DATABASE: fossilCatalog
            DB_USER: root
            DB_PASSWORD: root
            DB_HOST: "127.0.0.1"
            DB_PORT: 3306

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   uses: shogo82148/actions-setup-mysql@v1
                with:
                    distribution: "mariadb"
                    mysql-version: "10.5"
                    root-password: root
                    my-cnf: |
                        max_allowed_packet=999MB

            -   name: Setup PHP
                id: setup-php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: mbstring, intl, pdo_mysql, ctype, gd, iconv, yaml, zip

            -   name: Install composer dependencies
                run: composer install

            -   name: Setup environment
                run: composer setup

            -   name: Run Php cs-fixer
                run: composer fix-cs-dry

            -   name: Run PhpStan
                run: composer phpstan

            -   name: Run PHPUnit tests
                run: composer phpunit
